on: [push, pull_request]
name: Test
jobs:
  test:
    name: Ubuntu on node ${{ matrix.node }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [8, 12, 13]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: yarn global add lerna
    - run: yarn bootstrap
    - run: yarn run check
    - run: ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info
      env:
        CODECLIMATE_REPO_TOKEN: 18e1eef105275451c25392c4f6b07ae0cc4ca3f6c280f9ccfcad7a16c9068d47
